name: Update badges

on:
  schedule:
    # Runs at 8am UTC
    - cron: "0 8 * * *"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: ckarthik20/badge-readme@master
          CREDLY_USER: karthikc # optional, but default will use the same from github
